### ISSUE TITLE
Using directory option without including the directory folder

### ISSUE THREAD

**Issue by seagoj** [Keats/kickstart#64]
First off, great project! It really solves a problem for me.

Is there a way/could there be a way to use the files within the set `directory` option without adding the directory itself?

I have this to begin my template.toml:
```toml
name = "Kickstart"
description = "example"
kickstart_version = 1
directory = "template_root"
```
However, when i use this template, I get a `./template_root` when I really just expected the files in `./template_root`
