### ISSUE TITLE
[feature request] negation for only_if

### ISSUE THREAD

**Issue by TECHNOFAB11** [Keats/kickstart#73]
In your rust-cli template, there is a choice question for the license and another question for the author. I'd like to only ask for the author if a license was selected for my use case. But I cannot have more than one condition nor a way to negate them (not equals) I know of.
I don't know how the best UX would look like here, but probably the most straightforward way would be to add "operation" or something to `Condition`, which can then contain "equals" "not_equals" or so? :+1:

**Comment by Keats** [comment]
Maybe it could be `unless = { name = "license", value = "None" }`?

**Comment by Keats** [comment]
I'm still thinking about it. It would be nice use containment and such. Maybe we could just use a Tera expression? Something like `only_if = { expression = "license is defined" }`. This way you can just use whatever you want from Tera

**Comment by LukeCarrier** [comment]
This could be useful beyond variable declarations too, for instance, in `cleanup`:

```toml
[[cleanup]]
name = "nix_dev_shell"
value = "!= 'other'"
paths = ["nix"]

[[variables]]
name = "nix_dev_shell"
prompt = "What tools do you need?"
choices = [
  "nodejs_24",
  "other",
]
```
